### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by kanumuri9593** [sgratzl/chartjs-chart-graph#10]
When I try to install the package using npm getting 

npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://dssits.jfrog.io/dssits/api/npm/npm/chartjs-chart-graph

**To Reproduce**

1. 

**Expected behavior**

**Screenshots**

**Context**

- Version:
- Browser: 

**Additional context**

**Comment by sgratzl** [comment]
I don't know this npm registry:  https://dssits.jfrog.io

**Comment by sgratzl** [comment]
stale, closing for now
