### ISSUE TITLE
Tree graph corrupted (but not dendogram)

### ISSUE THREAD

**Issue by xopxe** [sgratzl/chartjs-chart-graph#11]
When I use the tree graph it get broken with redundant edges and a background. Dendogram with the same datasets, options, etc, works fine. 
I see the effect with my plots and even when viewing the samples (from https://codepen.io/sgratzl/pen/wvwNeWg , screencap attached, the top row are dendograms and look ok, the bottom are broken trees). 
Using Firefox 80.0 and Chromium 85.0.4183.83 on Linux (Ubuntu 20.04). 	

![Screenshot from 2020-09-02 22-20-40](https://user-images.githubusercontent.com/1254270/92060921-64fff100-ed6b-11ea-8175-573518b789b9.png)

**Comment by sgratzl** [comment]
should be fixed in v2.2.1
