### ISSUE TITLE
different link strengths in force directed graph

### ISSUE THREAD

**Issue by avitran0** [sgratzl/chartjs-chart-graph#115]
Can i add different link strengths for each link in a fdg? i know d3 supports it, but i cannot seem to get it to work for this library. IGraphEdgeDataPoint just seems to have a source and target, but no distance or strength like the d3 links have.

**Comment by sgratzl** [comment]
you should be able to customize the link force -> https://github.com/sgratzl/chartjs-chart-graph/blob/052d2b88464b9a871b5bd6ad8cadd8d30d9a3ad6/src/controllers/ForceDirectedGraphController.ts#L74 e.g by giving it a callback to determine the given object what the strength / distance should be

**Comment by avitran0** [comment]
i tried that, that function is only ran once, with the dataset object(?). i forked your codepen [here](https://codepen.io/avitrano/pen/rNEBwpL) to test it, so you can look yourself. the argument i in the ID3EdgeCallback of the strength function is also not a number as stated in the code, but a proxy object.

**Comment by sgratzl** [comment]
it seems like that this option is scripable via chart.js. So, it will call the function with the dataset object. What you can do and it seems to work it to wrap the function in another function 

![image](https://github.com/sgratzl/chartjs-chart-graph/assets/4129778/abe41113-46d0-48a6-aecc-ac0b12b62769)

the first function is being called from chart.js to resolve the option. The return value is the callback value used by D3.

**Comment by avitran0** [comment]
thank you, that seems to work. this should probably be reflected in the documentation and the types.
