### ISSUE TITLE
Pan with chartjs-chart-graph?

### ISSUE THREAD

**Issue by mossaiby** [sgratzl/chartjs-chart-graph#13]
Is there any (easy) way to add zoom / pan functionality to chartjs-chart-graph? I have tried chartjs-plugin-zoom and zoom works fine, but no pan.

Check this fiddle: https://jsfiddle.net/y8jm4q3u

**Context**

- Version: Chart.js: 2.9.4, Chart.Graphs: 2.2.1, Zoom plugin: 0.7.7
- Browser: Chrome Desktop 86.0.4240.111, Firefox 81.0.2

Any help would be greatly appreciated. Thank you!

**Comment by mossaiby** [comment]
Hi @sgratzl, any progress with this? Thanks!

**Comment by sgratzl** [comment]
sorry no idea why it isn't working and I don't know the internals of the plugin to investigate properly

**Comment by mossaiby** [comment]
Thanks, @sgratzl!

**Comment by sgratzl** [comment]
delaying for now till a chart.js 3.0.0 compatible version of the plugin is out.

**Comment by sgratzl** [comment]
seems to work out of the box
