### ISSUE TITLE
Is it possible to change the spacing between branches?

### ISSUE THREAD

**Issue by diego92sigma6** [sgratzl/chartjs-chart-graph#17]
Hi Samuel, the library is working wonders.
I've been able to display a taxonomical tree with lots of branches (~30)

I'm having the following question...
Is it possible to increment the space between each branch so some labels don't overlap?

**Screenshots / Sketches**
![image](https://user-images.githubusercontent.com/22083784/111193270-60c15580-8590-11eb-824a-d64521f4b379.png)
That's the currently configured tree. 

**Context**

- Version: 3.0.0-beta.9
- Browser: Chrome

**Comment by sgratzl** [comment]
the layout is determined by the number of nodes and the canvas/chart size. In your given example, I don't know how the vertical spacing should be increased given the number of nodes you wanna show

**Comment by diego92sigma6** [comment]
Thanks for the comment. It was indeed the canvas container size preventing the nodes from expanding. Setting the chart option "maintainAspectRatio" to false and then modifying the parent container element's width and height can allow the branches to be more spread out.
