### ISSUE TITLE
Dashed line in graph

### ISSUE THREAD

**Issue by dbflakes** [sgratzl/chartjs-chart-graph#18]
The documentation says that the config is derived from the line chart but it doesn’t seem to be working for lines.
I am trying to change the line to a dashed line by adding
`borderDash: [5, 5]`

But it causes the graph rendering to fail with the below error:

```
edgeLine.ts:58 Uncaught TypeError: Failed to execute 'setLineDash' on 'CanvasRenderingContext2D': The provided value cannot be converted to a sequence.
    at EdgeLine.draw (edgeLine.ts:58)
```

**Comment by sgratzl** [comment]
can you try out the latest .rc version, please

**Comment by dbflakes** [comment]
With the latest RC version, I am getting the error below:

```
./node_modules/chartjs-chart-graph/build/index.umd.js 346:62
Module parse failed: Unexpected token (346:62)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       const reset = mode === 'reset';
|       const firstOpts = this.resolveDataElementOptions(start, mode);
>       const sharedOptions = this.getSharedOptions(firstOpts) ?? {};
|       const includeOptions = this.includeOptions(mode, sharedOptions);
|       const {
```

**Comment by sgratzl** [comment]
seems like the code is using ES2020 features that your setup is not capable of yet. I configured TypeScript to compile to ES2019 instead in the meanwhile you can use babel to transpile this code

**Comment by sgratzl** [comment]
please try the new 3.0.1 version
