### ISSUE TITLE
test chartjs-plugin-dragdata plugin

### ISSUE THREAD

**Issue by sgratzl** [sgratzl/chartjs-chart-graph#2]
https://github.com/chrispahm/chartjs-plugin-dragdata

**Comment by sgratzl** [comment]
smooth and easy: https://codepen.io/sgratzl/pen/XWrOgpy

**Comment by dbflakes** [comment]
This functionality is broken with chart.js 3.0.0
Any plan to support dragging for the latest version?

**Comment by szlezakbartosz** [comment]
Does not work with chartjs in version 4.0.0 too. Any updates on this?

**Comment by szlezakbartosz** [comment]
That's helpful, thank you! :)
