### ISSUE TITLE
None of the examples on codepen are working

### ISSUE THREAD

**Issue by pgonzaleznetwork** [sgratzl/chartjs-chart-graph#21]
When I go to https://codepen.io/sgratzl/pen/mdezvmL or any of the other examples, nothing loads on the iframe.

**To Reproduce**

1. Go to https://codepen.io/sgratzl/pen/mdezvmL or any of the other examples in the repo

**Expected behavior**

I should see the chart in the codepen iframe. Instead I see a blank screen. Happens in both Firefox and Chrome.

**Context**

- Browser: Latest chrome and firefox on MacOS

**Comment by sgratzl** [comment]
some of the examples were linking to the old version of the plugin and chart.js should be fixed
