### ISSUE TITLE
Basic Implementation

### ISSUE THREAD

**Issue by glimpsedchaos** [sgratzl/chartjs-chart-graph#22]
Finished upgrading to ChartJS v3 and really liking the plugins you have here. Specifically the tree after working in the D3 world.

How do I go about implementing? Meaning other plugins state something like "To create a sankey chart, include chartjs-chart-sankey.js after chart.js and then create the chart by setting the type attribute to 'sankey'".

Easy enough. But I can't find any equivalent chartjs-chart-graph.js to reference. Everything in the samples are "index.umd.ts".

I've tried bringing the entire folder structure into my project and reference but end up with errors ranging from "Cannot use import statement outside a module" to "Error: "dendogram" is not a registered controller.".

I am building in just HTML5/Javascript environment.

Any direction would be greatly appreciated.

**Comment by sgratzl** [comment]
the examples such as https://github.com/sgratzl/chartjs-chart-graph/blob/main/samples/directed.html and the CodePens: https://codepen.io/sgratzl/pen/mdezvmL are the main way how my plugins show their functionality. e.g. if you go to the codepen and export it (bottom right there is a button for it) you should get a zip file with a setup similar to the one you are looking for.
