### ISSUE TITLE
lineBorderColor and borderColor not working as expected

### ISSUE THREAD

**Issue by SteffiPeTaffy** [sgratzl/chartjs-chart-graph#23]
`lineBorderColor` and `borderColor` not working as expected on a `forceDirectedGraph`

- When I set the `lineBorderColor` property to a static value the edges are not displayed in the correct color (default grey color). 
- When I set the `borderColor` property to a static value the edges and the borders of nodes and the legend are all coloured correctly. 
- Both properties don't seem to work when given a [function](https://www.chartjs.org/docs/latest/general/options.html#scriptable-options) instead of a static value.
I made a little [fiddle](https://jsfiddle.net/q71a4xku/2/) that `console.logs` the callback parameters to better illustrate the problem.

I am also not sure if the scripted option is available to `lineBorderColor` and `borderColor` for this plugin.

I am using:
- Version: [Chart.js v3.3.2](https://unpkg.com/chart.js@3.3.2/dist/chart.min.js) and [chartjs-chart-graph@3.1.0](https://unpkg.com/chartjs-chart-graph@3.1.0/build/index.umd.min.js)
- Browser: Chrome on Mac

**Comment by sgratzl** [comment]
can you try using `edgeLineBorderColor`? this plugin use a custom line element implementation and thus needs a different prefix.
