### ISSUE TITLE
How to start App after cloning repository ?

### ISSUE THREAD

**Issue by Prince-Hamza** [sgratzl/chartjs-chart-graph#29]
i tried running npm start but nothing on localhost:3000 or 5000 or 8080 is found.cant find any other solution ?

**Comment by Prince-Hamza** [comment]
How do i use or utilize this plugin???

**Comment by sgratzl** [comment]
have you been taken a look at the samples? https://github.com/sgratzl/chartjs-chart-graph/tree/main/samples
