### ISSUE TITLE
Make this extension available without npm

### ISSUE THREAD

**Issue by JosephChataignon** [sgratzl/chartjs-chart-graph#41]
It would be great to be able to use this extension (and the other ones you've made) client-side, which cannot be done currently since the only way to install is through npm. Ideally it would be a single js file that can be loaded via a CDN, just like the original Chart.js.

**User story**

My use case is a small application to provide charts based on data given by the user. The whole thing fits in a few JavaScript files that are executed client-side. In fact, the whole thing works as a static site. I can use vanilla Chart.js, but this extension only works server-side currently, so I cannot use it.

**Comment by sgratzl** [comment]
if you take a look at the codepens e.g. https://codepen.io/sgratzl/pen/jObedwg and export it you will see that it is actually using a CDN to access the library and uses pure client side scripting without a build process

**Comment by JosephChataignon** [comment]
Oh right ! Maybe adding the CDN in the github readme would help other people in my situation ?
