### ISSUE TITLE
Support DOT graphviz format

### ISSUE THREAD

**Issue by s4m0r4m4** [sgratzl/chartjs-chart-graph#6]
It would be great if this plugin supported creating trees from the GraphViz DOT standard format: https://www.graphviz.org/doc/info/lang.html. That would enable more use cases. 

**User story**
I'm currently using chart.js for plotting data, and vis-network (https://visjs.github.io/vis-network/docs/network/) for displaying tree/hierarchical data because the source produces it in DOT format. This results in a large chunk of rendering-related code in my final software package that could be significantly reduced if I could simply use this plugin with chart.js.

Just an idea, thanks for your library!

**Comment by sgratzl** [comment]
I think an adapter function that converts the DOT format to chart.js internal format would be useful. I take a look how complex the language is and how to map it.

**Comment by sgratzl** [comment]
since the dotparser libraray (https://github.com/anvaka/dotparser/) is quite large, I decided to split the parsing up in a separate project: https://github.com/sgratzl/chartjs-chart-graph-dot-parser

**Comment by s4m0r4m4** [comment]
Thanks! I will check this out soon, I appreciate the quick response!
