### ISSUE TITLE
There is no example for the fifth image

### ISSUE THREAD

**Issue by jeeva-thangavel** [sgratzl/chartjs-chart-graph#63]
I'm trying to create fifth image in the readme, but was not able to create it. facing `core.registry.js:178 Uncaught Error: "dendogram" is not a registered controller.` issue can anyone please help me to solve this issue, what all are the controller I can assign or use, or how can I solve the issue

**Comment by sgratzl** [comment]
https://codepen.io/sgratzl/pen/PodjzJm works just fine
