### ISSUE TITLE
Rotate forceDirectedGraph

### ISSUE THREAD

**Issue by sk0gen** [sgratzl/chartjs-chart-graph#7]
Hi. I use your example with 'forceDirectedGraph' and i provided my example json.

```
const data =`
{
  "nodes": [
    {
      "id": "e1049793-0c77-4f32-b95d-8067613798d9"
    },
	{
      "id": "c315f4a6-5f1d-464d-8f7b-e369d7d205cf"
    },
	{
      "id": "524f4f3a-edf1-484b-9e5a-54f347937e27"
    },
	{
      "id": "b55af307-e2ce-4d27-8851-5f204770d922"
    },
	{
      "id": "df0b4f7d-8b70-4884-b249-635010d95be5"
    }
    
  ],
  "links": [
    {
      "source": "e1049793-0c77-4f32-b95d-8067613798d9",
      "target": "c315f4a6-5f1d-464d-8f7b-e369d7d205cf"
    },
	{
      "source": "c315f4a6-5f1d-464d-8f7b-e369d7d205cf",
      "target": "524f4f3a-edf1-484b-9e5a-54f347937e27"
    },
	{
      "source": "c315f4a6-5f1d-464d-8f7b-e369d7d205cf",
      "target": "b55af307-e2ce-4d27-8851-5f204770d922"
    },
	{
      "source": "524f4f3a-edf1-484b-9e5a-54f347937e27",
      "target": "df0b4f7d-8b70-4884-b249-635010d95be5"
    },
	{
      "source": "b55af307-e2ce-4d27-8851-5f204770d922",
      "target": "df0b4f7d-8b70-4884-b249-635010d95be5"
    }
  ]
}`
```

And it generates graph i wanted. But furthermore i want to have first node at the top and last note at the bottom. 
Currently I have left side, but I want right side. Do you know how can i do that?
And I want labels to be visible all the time.
![image](https://user-images.githubusercontent.com/28295528/82437023-02723600-9a97-11ea-9200-b8bb27c99726.png)

- Version: Newest
- Browser: Chrome

**Comment by sgratzl** [comment]
have you tried fixing the desired not positions by providing an `x` or `y` value?

**Comment by sk0gen** [comment]
Ohh. That's work, but it will be kinda hard to generate x,y for all data which is provided dynamically ;/. But thanks anyway

**Comment by sgratzl** [comment]
the nature of force directed layouts are not that predictable. 

there are advanced graph layout libraries doing a better job, such as 
 * https://ialab.it.monash.edu/webcola/
 * https://github.com/dagrejs/dagre
 * https://www.graphdracula.net/

and others. One can extends the `Graph` controller of this library and implement a custom `doLayout` logic using one of those.

**Comment by sgratzl** [comment]
btw. I jut created https://github.com/sgratzl/chartjs-chart-graph-dagre which is an extension to this library using the dagre layouting library. side note: the bundling size is huge, since the default dagre lib doesn't support tree shaking

**Comment by sk0gen** [comment]
Wow nice! But you example is using <script src="../build/Chart.Graphs.Dagre.js"></script>
How to change it to use installed Graph.Dagre from npm?

**Comment by sgratzl** [comment]
depending on your setup and needs you could
 * install it via npm; `npm i chartjs-chart-graph-dagre`
 * download the released binary: https://github.com/sgratzl/chartjs-chart-graph-dagre/releases
 * link to it via a CDN such as
   * https://unpkg.com/chartjs-chart-graph-dagre
   * https://cdn.jsdelivr.net/npm/chartjs-chart-graph-dagre

**Comment by sk0gen** [comment]
Ahh. Yea. It works. One more question. Is there possibility to show labels all the time?

**Comment by sgratzl** [comment]
not within the library but there is https://chartjs-plugin-datalabels.netlify.app/. However, I don't know how compatible these things are atm.
