### ISSUE TITLE
Stop the Simulation

### ISSUE THREAD

**Issue by Gykonik** [sgratzl/chartjs-chart-graph#70]
Is there a way to stop the simulation using `forceDirectedGraph`? :)

**Comment by sgratzl** [comment]
the controller has a `stopLayout` method

https://github.com/sgratzl/chartjs-chart-graph/blob/5f0a4a6fb6418b8e1aaa00f25c4dfa8e7f35173e/src/controllers/ForceDirectedGraphController.ts#L330

**Comment by Gykonik** [comment]
How do I access the controller? I tried using `Chart.registry.getController("forceDirectedGraph");`, which gives me some sort of controller  - but there I cannot call `stopLayout()`

**Comment by sgratzl** [comment]
can you try `chart.getSortedVisibleDatasetMetas()[0].controller.stopLayout()`

**Comment by Gykonik** [comment]
Thanks for the answer. However, that gives me the following type error `TS2339: Property 'stopLayout' does not exist on type 'DatasetController  , Element , number | ... 7 more ... | (ITreeNode & { ...; })>'` and thus doesn't seem to work.
