### ISSUE TITLE
Ordering of `edgeLineBorderColor`

### ISSUE THREAD

**Issue by Gykonik** [sgratzl/chartjs-chart-graph#71]
I'm encountering an issue with the edge color in the chartjs-chart-graph library. While the graph itself is rendering correctly, the edge color is not being applied as expected. I have tried using other graph libraries where the edge color works perfectly, but it seems to behave differently in this particular case.

Typically, the edge color is determined based on the color of the start node. However, in the graph produced by chartjs-chart-graph, this is not the case. I have verified that the data is correct by using other graph libraries, so the issue seems to be specific to this library.

Here is a snippet of my code:

```
const borderColors = this.inputGraph.edges.map((d: any) => d.color);
// ...
data: {
  labels: this.inputGraph.nodes.map((n: any) => n.id + ""),
  datasets: [
    {
      pointBackgroundColor: this.inputGraph.nodes.map((n: any) => {
        return n.color;
      }),
      pointBorderColor: this.inputGraph.nodes.map((n: any) => {
        return n.color;
      }),
      pointRadius: 2,
      data: this.inputGraph.nodes,
      edges: this.inputGraph.edges,
      edgeLineBorderColor: borderColors,
      borderWidth: 1
    },
  ],
},
``` 

I am using normal hex values for the edge color. Can anyone help me understand why the edge color is not being applied correctly in the chartjs-chart-graph library? Any suggestions or insights would be greatly appreciated.

If you need additional information, feel free to ask and I'll provide it as soon as possible!

**Comment by sgratzl** [comment]
why not using a context function instead of relying on indices? Then you have access to the edge object directly
