### ISSUE TITLE
support directed edges

### ISSUE THREAD

**Issue by sgratzl** [sgratzl/chartjs-chart-graph#9]
It would be great if directed edges are supported as in an arrow head to indicate the direction of the edge

**User story**

support of directed graphs

**Additional context**

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/83974638-33ec5d80-a8ef-11ea-83ce-1cc7aacbf9e9.png)

**Comment by casidiablo** [comment]
So how do I enable this?

**Comment by sgratzl** [comment]
so far there is only support in the latest alpha version which is targeting chart.js 3.0.0 e, g. https://github.com/sgratzl/chartjs-chart-graph/blob/develop/samples/directed.html
